basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    get:
      operationId: find-users
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetUsers
    post:
      consumes:
      - application/json
      operationId: create-user
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: CreateUser
swagger: "2.0"
