basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      operationId: create-user
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: CreateUser
swagger: "2.0"
